### ISSUE TITLE
running xenocp with singularity

### ISSUE THREAD

**Issue by xinyuwen** [stjude/XenoCP#12]
the xenocp was installed with singularity container. Running these commands:

Xenocp -I /my_input_bam -o /my_input_bam_xenocp.bam -t bam -V STRICT (I also tried LENIENT and SILENT, with the same result)

I got the following error message:

.
.
.
Ignoring SAM validation error: ERROR: Record 408498785, Read name HWI-ST495_147604559:7:2316:1402:81558, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498787, Read name HWI-ST495_147604559:7:2316:16574:8716, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498790, Read name HWI-ST495_147604559:7:2316:3056:45367, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498792, Read name HWI-ST495_147604559:7:2316:3447:5772, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498793, Read name HWI-ST495_147604559:7:2316:5180:64922, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498794, Read name HWI-ST495_147604559:7:2316:6478:51751, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498796, Read name HWI-ST495_147604559:7:2316:8788:5145, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498797, Read name HWI-ST495_147604559:7:2316:9631:43140, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 408498798, Read name HWI-ST495_147604559:7:2316:9821:34808, MAPQ should be 0 for unmapped read.
408498798 read
         0 checked
noCP_test/processed_DATA/SJACT013760_D1_xenocp.bam -t bam -V STRICT TA/SJACT013760_D1.bam -o /data/khanlab3/xen
DEBUG   2020-03-09 21:44:48     BlockCompressedOutputStream     Using deflater: Deflater
    844951 read
         0 checked
         0 written
         0 ties

Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 844953, Read name HWI-ST495_147604559:7:1305:17594:80654, MAPQ should be 0 for unmapped read.
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:441)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:665)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:650)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:620)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:545)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:519)
        at org.stjude.compbio.xenocp.CreateContamLists.autoProcess(CreateContamLists.java:72)
        at org.stjude.compbio.xenocp.CreateContamLists.main(CreateContamLists.java:333)

The input bam is from this StJude study EGAS00001002528

**Comment by mcrusch** [comment]
Based on the error message, it looks to me like setting validation stringency to SILENT is not actually being applied at the CreateContamLists step.  However, as I look at the cwl, it looks to me like no matter what you do, it should be set to SILENT.  It doesn't surprise me that it ignores your setting, but it does surprise me that it's acting STRICT instead of SILENT.  Perhaps related, I also don't recognize the command line you pasted in.  Are you using a custom wrapper?  Can you provide some more detail about how you're invoking it?

**Comment by xinyuwen** [comment]
I took these steps:

module load singularity

export SINGULARITY_BINDPATH="/gpfs,/spin1,/data,/lscratch,/scratch,/fdb,/vf"  #To mount local storage to the container

singularity shell xenocp.sif
Singularity> /opt/xenocp/bin/xenocp -i /data/khanlab3/xenoCP_test/DATA/SJACT013760_D1.bam -o /data/khanlab3/xenoCP_test/processed_DATA/SJACT013760_D1_xenocp.bam -t bam -V LENIENT #I tried all three options “STRICT|LENIENT|SILENT” They all gave the same result

I did not use custom wrapper.

**Comment by mcrusch** [comment]
The current image does not have a xenocp executable in /opt/xenocp/bin:

> root@e52a709b6625:/# ls /opt/xenocp/bin/xenocp
> ls: cannot access '/opt/xenocp/bin/xenocp': No such file or directory

So, I would start by updating your git repo and rebuilding the image.

**Comment by xinyuwen** [comment]
I have the program here:

Singularity> cd /opt
Singularity> ls
picard  tools-sam  xenocp
Singularity> cd xenocp/
Singularity> ls
bin  cwl  lib
Singularity> cd bin
Singularity> ls
xenocp  xenocp.bat
Singularity> pwd
/opt/xenocp/bin

Maybe it is a custom installation? I have to sys. Admin cc’d so he can give us some idea about the installation.

**Comment by xinyuwen** [comment]
Hi All,

I did not do a custom installation of xenocp but rather I converted the docker image of xenocp to singularity without any changes. The link to the image is:

https://hub.docker.com/r/adthrasher/xenocp

The image is provided by one of the xenocp developers (Andrew Thrasher) on his dockerhub account.

Thanks.


--
Antonio Ulloa, PhD
NIH HPC Support Scientist
Publicis Sapient Contractor
https://hpc.nih.gov
301.827.6935

________________________________________
From: Wen, Xinyu (NIH/NCI) [C] <wenxi@mail.nih.gov>
Sent: Wednesday, March 11, 2020 12:01 PM
To: 'stjude/XenoCP'; stjude/XenoCP
Cc: Author; Ulloa Perez, Antonio (NIH/CIT) [C]
Subject: RE: [stjude/XenoCP] running xenocp with singularity (#12)

I have the program here:

Singularity> cd /opt
Singularity> ls
picard  tools-sam  xenocp
Singularity> cd xenocp/
Singularity> ls
bin  cwl  lib
Singularity> cd bin
Singularity> ls
xenocp  xenocp.bat
Singularity> pwd
/opt/xenocp/bin

Maybe it is a custom installation? I have to sys. Admin cc’d so he can give us some idea about the installation.

**Comment by xinyuwen** [comment]
FYI: the "xenocp" executable is in  "/opt/xenocp/bin" as shown below:

______________
Singularity> pwd
/opt/xenocp/bin
Singularity> ./xenocp
usage: java org.stjude.compbio.xenocp.CreateContamLists [OPTION]
            CONTAM_BAM1,...
            Looks for contamination in a sam/bam file by finding a
            better mapping in any of a list of contamination bams.
            The main output is a list of read names that are called as
            contamination.  You may also use -t to write records that
            were called as 'ties' to an output sam/bam file for
            review.
            This will operate on single- or paired-end data, but the
            input and contam bams must be 'logically' both single or
            or paired.  A read is considered 'logically' paired if it
            is actually paired or if it is single end but has a
            suffix of [non-alphanumeric char][12] that indicates
            read number in the pair.
            CAVEAT: All bams must have the NM tag, containing edit
            distance!
 -i <arg>   input file to use if not stdin
 -o <arg>   output contam reads file if not stdout
 -t <arg>   output sam/bam to which to write ties
 -V <arg>   validation stringency: STRICT, LENIENT, or SILENT (default:
            SILENT)
Singularity>
__________________

--
Antonio Ulloa, PhD
NIH HPC Support Scientist
Publicis Sapient Contractor
https://hpc.nih.gov
301.827.6935

________________________________________

**Comment by mcrusch** [comment]
I'm sorry for the long delay.  I thought I had replied already.  The images in Andrew's Docker Hub are from various older test builds.  You'll need to pull from GitHub and build the image, per the current README.

**Comment by AnaICastilloO** [comment]
Hi Dr. Michael Rusch: 

Greetings, I’ve been trying to install XenoCp and build the container from the resources available at XenoCp’s GitHub. However, Compute Canada, the cluster where I currently work, has told me it does not support Docker and uses Singularity instead. Unfortunately, I don’t have root access and cannot create the singularity container from a Dockerfile. 

Accordingly, they have asked me if it is possible to ask the authors of XenoCp for providing a container that has already been built and available on Dockerhub so it can be used directly by Singularity. I don’t know if this is possible for you. Of course, I understand if this not feasible. 

Thank you so much for your time in reading this email and for your help. I would appreciate it. 
 
Kindest Regards.

**Comment by adthrasher** [comment]
Hi @AnaICastilloO, 

Due to licensing restrictions of software required by XenoCP, we are unable to provide a built image. One option to try would be for you to build the Docker image locally and upload it to a private repository on Docker hub. Then you should be able to build it on the cluster using Singularity and providing your Docker hub credentials. 

Andrew

**Comment by AnaICastilloO** [comment]
> Hi @AnaICastilloO,
> 
> Due to licensing restrictions of software required by XenoCP, we are unable to provide a built image. One option to try would be for you to build the Docker image locally and upload it to a private repository on Docker hub. Then you should be able to build it on the cluster using Singularity and providing your Docker hub credentials.
> 
> Andrew

Dear Dr. Andrew: 
Thank you so much for your soon answer. It is quite useful. I will try that way! Thank you again.
