### ISSUE TITLE
Identification of mouse reads

### ISSUE THREAD

**Issue by RaphaelHablesreiter** [stjude/XenoCP#14]
Hi,

is there a possibility to fine tune the filtering of contaminated reads?
After processing my *.bam-file with your pipeline some reads with the same kind of "error" bases that have been filtered are overlooked.
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/23275967/86785426-e7697e80-c062-11ea-9e72-20f616e463a1.png">
Can you help me with this problem?

Many thanks in advance!

Regards,
Raphael

**Comment by mcrusch** [comment]
There really isn't anything in the way of tuning parameters.  However, that signature definitely looks suspect.  So, if you'd like, I can dig in deeper and try to figure out what is going on.  If so, is there any chance you could provide the input file you used?  Just a small slice of the BAM in this region would be sufficient.

**Comment by RaphaelHablesreiter** [comment]
Thank you very much. I have attached the BAM at this region (17:79478400-79478600). 
[example.zip](https://github.com/stjude/XenoCP/files/4901485/example.zip)

**Comment by mcrusch** [comment]
Thanks for providing that.  The contaminant reads are very easy to see in the input, so it's a good example.  Unfortunately, I was unable to reproduce.  The output I got looks clean to me:
[example_output.zip](https://github.com/stjude/XenoCP/files/4904388/example_output.zip)

Can you tell me more about how you ran it?  Was it local from gradle build, local using container, on DNAnexus, etc.?

**Comment by RaphaelHablesreiter** [comment]
Thank you for your time. I ran it local from gradle build and everything completed successfully. This means that some parts of my local build is not running in the right way?

**Comment by RaphaelHablesreiter** [comment]
I tried the docker build and got the same results as with my local build.

**Comment by mcrusch** [comment]
OK, so I see that although several reads got cleaned, it looks like there are some that remain.  I'll look into this closer.

**Comment by RaphaelHablesreiter** [comment]
Thank you very much for your time!

**Comment by mcrusch** [comment]
What I'm seeing in these reads that are not cleansed is that they are contaminated with Illumina adapters.  This is based on a spot-check of a few reads.  Internally, XenoCP uses bwa backtrack in single-end mode to perform the alignment to mouse, and that is not able to perform the local alignment required for adapter-contaminated reads.  In the future, we could consider en enhancement, replacing single-end bwa backtrack with bwa mem (which didn't exist when this was written--it has been that long) or some other algorithm, but that has not been evaluated.  For now, I would say to perform adapter trimming on your input data pre-mapping and then try again.

**Comment by RaphaelHablesreiter** [comment]
Thank you! You helped me a lot.
