### ISSUE TITLE
wdl/tools: XenoCP 3.1.4 tasks use 3.1.0 container image

### ISSUE THREAD

**Issue by zaeleus** [stjude/XenoCP#28]
The WDL tasks for XenoCP 3.1.4 use XenoCP 3.1.0 rather than 3.1.4, e.g., https://github.com/stjude/XenoCP/blob/3.1.4/wdl/tools/xenocp.wdl#L38.

**Comment by adthrasher** [comment]
3.1.4 has been re-released to resolve this issue.
