### ISSUE TITLE
Add Singularity support

### ISSUE THREAD

**Issue by mcrusch** [stjude/XenoCP#51]
Make changes necessary to support easily executing using Singularity.

Likely this will only include changes to the README.  However, if issues arise requiring additional changes, they should be done under this issue as well.

- [x] In README, wherever we have a docker run command, add the corresponding singularity run command
- [x] Include --containall in Singularity commands
- [x] Double-check the existing note about -W.  It should possibly be reworded or moved.

**Comment by adthrasher** [comment]
@mcrusch - As part of #49, I updated the README with singularity information. Take a look and see if you think that adequately addresses this issue.
