### ISSUE TITLE
Bug: unmapped read pairs are not preserved in output

### ISSUE THREAD

**Issue by mcrusch** [stjude/XenoCP#9]
Unmapped read pairs (with empty reference name) are not being included in the final BAM.  Presumably, this was introduced with the FASTQ extraction optimization, since no-reference reads are not extracted there.

**Comment by adthrasher** [comment]
My suggestion would be to use sambamba to pull the reads during the splitting step, `sambamba view -F "ref_name =~ /\*/"`. Then just pass an additional bam to the merge step at the end.

**Comment by adthrasher** [comment]
Closing now that #10 is merged.
